name: Run Python Script

on:
  schedule:
    # Runs every Friday at midnight
    - cron: '0 0 * * 6'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Disable automatic token authentication

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py

    - name: Commit files
      run: |
          git config user.email "rvibek@gmail.com"
          git config user.name "rvibek"
          git remote set-url origin https://rvibek:${{ secrets.GH_PAT }}@github.com/rvibek/help_unhcr_org.git
          git add .
          git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
