name: Run Python Script

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Disable automatic token authentication

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python main.py

    - name: Verify file content and Git status
      run: |
        echo "Content of unhcr_help_pages.json:"
        cat unhcr_help_pages.json
        echo "Git status:"
        git status

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "rvibek@gmail.com"
        git config --global user.name "rvibek"
        git remote set-url origin https://rvibek:${{ secrets.GH_PAT }}@github.com/rvibek/help_unhcr_org.git
        git add unhcr_help_pages.json
        git diff-index --quiet HEAD || git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main
