name: Run Python Script

on:
  schedule:
    # Runs every Friday at midnight
    - cron: '0 0 * * 6'
  workflow_dispatch:  # Allows manual triggering


jobs:
    fetch:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.x"
  
        - name: Install dependencies
          run: pip install -r requirements.txt
  
        - name: Run help_unhcr_help
          env: 
            EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          run: python main.py
  
        - name: Commit and push CSV files
          env:
            GITHUB_ACTIONS_BOT_TOKEN: ${{ secrets.GITHUB_ACTIONS_BOT_TOKEN }}
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add -A
            git commit -m "update data" -a
        
  
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # GITHUB_ACTIONS_BOT_TOKEN: ${{ secrets.GITHUB_ACTIONS_BOT_TOKEN }}
            branch: main  